### PR TITLE
Fix macOS test issue and use the new version of UnitTesting

### PR DESCRIPTION
**Pull request by randy3k**
When the view is created, [on_activate_async][1] is triggered, and it runs `manager.settings_for_view()`. 

[1]: https://github.com/niosus/EasyClangComplete/blob/1d40ad4f3d1bc6cbf8c82b960e4ca5dae592fcde/EasyClangComplete.py#L108-L108

### CODE REVIEW

**Comment by randy3k** [comment]
There is still a race condition between `on_activate_async` and the testcase. I guess you may need to either disable `on_activate_async` or waiting until `on_activate_async` is triggered.

**Comment by niosus** [comment]
So, does this mean, that if I open a view in multiple tests I cannot expect this view to be in focus as some other test of mine could have opened another view on top?

**Comment by niosus** [comment]
@randy3k thinking more about it, running `on_activate_async` is probably not what I want for unit testing. I don't always want to run the full plugin on a new view. I am doing unit testing to test isolated behaviors of different components. 

I don't see how to eliminate the side effects of such a race condition. You said there is a way to disable `on_activate_async`. Would you have hints on how to do this?

**Comment by randy3k** [comment]
The easiest way is probably using the [view settings][1].

[1]: https://github.com/niosus/EasyClangComplete/pull/149/commits/1078de6dcdc0d056aa612111e388e967bdd72229#diff-4409a2e453c6592494f394ff99b8508dR116

**Comment by niosus** [comment]
This is great! Thanks a lot!

**Comment by randy3k** [comment]
Feel free to close this PR if you want to implement it differently.

**Pull request merged**
