### PR TITLE
Changed popup maximum dimensions from absolute units to proportion of…

### PR DESCRIPTION
**Pull request by detly**
… view.

Currently the popups are wider than my (portrait mode) screen. The simplest fix I could see was to make it proportional to the view dimensions instead. This might have some drawbacks, but I'm happy to take suggestions.

### CODE REVIEW

**Comment by niosus** [comment]
This looks good to me, but I wonder why you have this issue in the first place. The window should not be able to span further than the size of sublime text itself. At least that is how it functions for me.

I can't say that I like to stop it at view size, as I usually divide my view into 2 or 3 columns and the view would constrain the popups to one pane.

**Comment by niosus** [comment]
Also @detly could you please rebase on current dev? I have fixed the issues in the build system.

**Comment by detly** [comment]
Hmm okay. I initially thought I'd report it as a bug, but then I dug around in the source and thought it might be an easy fix, and why report a bug when you can do a PR instead :wink: 

Buuuut thinking about it I don't think this is the best solution, mainly for the reason that you say (also, if ST isn't maximised it'd be fine for a tooltip to extend beyond the view).

> The window should not be able to span further than the size of sublime text itself. At least that is how it functions for me.

I wonder if this is because your monitor width is > 1800px, and so it hits the max size before it hits the monitor bounds.

**Comment by niosus** [comment]
Ok, so I checked it. The behavior is the following:
- if the popup fits to screen it appears at the cursor
- if the popup appears so close to the border that it does not fit but there is space to the left of the cursor it will be moved
- if the popup is too large, it gets cropped at the window border and a horizontal scroll bar appears.

I am using FullHD screen everywhere, so yeah, I do have more than 1800 px. 

I have changed the value to 2400 just for tests and see the behavior that you described. The popup is not fully seen and hides behind the *left* border of the screen. I believe this should be targeted on the sublime text level.

**Comment by detly** [comment]
Or maybe the `mdpopups` level? Doesn't that define a bunch of CSS on top of
STs? I'm honestly not sure.

**Comment by niosus** [comment]
We can open an issue at https://github.com/facelessuser/sublime-markdown-popups and see what @facelessuser has to say about it :laughing:

**Comment by facelessuser** [comment]
CSS has nothing to do with the issues you are experiencing.  Mdpopups just provides a wrapper around Sublime's popup API.  We pass all related parameters to Sublime's API.

You define the max width and height you prefer via the API.  If your popup is ever too big for the window, and Sublime can't move it to fit the window, it will truncate the popup.  That is not controlled by mdpopups, but by Sublime itself.

At this time I have no plans to provide any complexity to adjust popups for screen size, I leave that up to plugins.

**Comment by facelessuser** [comment]
Reference to mdpopups documentation: http://facelessuser.github.io/sublime-markdown-popups/api/#show-popup.

**Comment by facelessuser** [comment]
Sublime may try to wrap content, but code blocks are done in such a way that they don't wrap, but I believe we have an option to allow them to wrap if desired. That could help, but might make some code blocks less readable. Not sure how you use mdpopups; you might not even be using code blocks.

So in short, Sublime will do it's best to wrap, position, and size your popup to make it fit. It will try to wrap content it can to make it smaller if it reaches max size, but if it can't, it moves the window to be completely in view, but again, if it is still too big it will get truncated.

This logic generally seems to make sense. Even OSs will do the same. In general, play with max size, and if that is not enough, and you are using code blocks that are too big, you can try disabling wrapping prevention. If you aren't using really wide code blocks, then all you can do is play with max size.

**Comment by detly** [comment]
Just ran into this again and remembered this PR. Did you want to do anything about this?

**Comment by niosus** [comment]
I am still concerned that the view width is enough. Maybe whole window width @detly ?

@facelessuser I understand your reasoning here. It would make sense to limit the size of the popup byt the size of the screen, I guess. Currently, the popup that must show reeeeaaaaly wide code blocks will try to move itself so that the right side of the code block touches the right border of the screen, which hides everything on the left side of the popup. I still have a feeling that this is a suboptimal default behavior, but I do understand that there might really be no better alternative available.

**Comment by facelessuser** [comment]
@niosus, what is your suggestion?

1. Mdpopups allows you to enable wrapping on code blocks if desired.

2. Mdpopups allows you to specify max widths and heights for your popups. You could calculate the width you desire and set those.

Do none of these work?  I'm not sure what you've tried and how they did or did not work for you. I would most likely start there.  If you can detail for me what your issue is with the current available API, and how it doesn't work, maybe we could talk about this a bit more. Currently, I'm not sure yet what is desired.

Mdpopups has a number of features to control this behavior, but you'd have to decide on a solution -- that I can't do for you.  If you have some issues with some of these features, or a suggestion for a feature Mdpopups can't already do, I would be happy to consider a proposal.

**Comment by niosus** [comment]
I was not aware of the code wrapping option. I guess it might be of interest here, what do you think @detly? 

I guess the main issue @facelessuser is that we don't know how big to set the window or when to wrap the code. I don't really have a suggestion here unless we can get the size of the current window from sublime text (`sublime.Window` doesn't seem to provide this).

**Comment by niosus** [comment]
Yep, that makes sense. Anyway, as there is no way to find the size of the window, there is no blame whatsoever on MdPopups 😆 

I believe a possible solution would involve either wrapping the code or giving the user an option to choose the maximum popup size from within the plugin settings.

**Comment by facelessuser** [comment]
You could make both of those options: wrapping and width. Then you can let your user tweak and fiddle and hopefully stop bugging you :smile:.

**Comment by detly** [comment]
Personally I think the best options are either (1) wrapping or (2) scrolling the popup viewport. I don't think #2 is available, but when I tried to implement #1 I couldn't figure out how to set wrapping in the popup. It was a while ago, so I actually can't remember where I hit a wall, but if you know off the top of your head @facelessuser it'd save me a bit of time hunting :grin:

**Comment by facelessuser** [comment]
@detly, it's in the documentation: http://facelessuser.github.io/sublime-markdown-popups/api/#show-popup.  Look at `allow_code_wrapping`.

**Comment by detly** [comment]
Thanks, not sure how I missed that. I'll modify the PR.

**Comment by facelessuser** [comment]
Maybe it's new sense when you originally issued your PR.  I can't remember.

**Comment by niosus** [comment]
I will close this for the lack of activity. Please reopen if needed.

**Comment by detly** [comment]
I'm just revisiting this now. I have the popup dimensions working, but code wrapping is proving tricky. According to the [Sublime Markdown Popups API docs](http://facelessuser.github.io/sublime-markdown-popups/api/#show-popup), the `allow_code_wrapping` argument is deprecated in favour of the `allow_code_wrap: true` key in YAML frontmatter. I am inserting this into the markdown document produced for the popup so the result looks like this:

```

---
allow_code_wrap: true
---
!!! panel-info "ECC: Info"
    ## Declaration: ##
    int [tcpip_adapter_init](/home/me/Code/esp-streamer/main/esp_streamer_main.c:38:5) ()
```

It seems to have no effect, the code boxes still don't break and require scrolling. @facelessuser - am I doing this right?

**Comment by facelessuser** [comment]
I don't know how you are running things. Do you have repo with an example?  The code you posted above has a new line at the start.  Currently, the frontmatter must start on the first line.

**Comment by detly** [comment]
For some reason the PR didn't update. I'll open a new one and discuss
there. But the newline is also in the constructed document, so maybe that's
the issue.

**Pull request closed without merging**
