### PR TITLE
Allow .clang-complete file

### PR DESCRIPTION
**Pull request by niosus**

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
@niosus, are you reconsidering this?

**Comment by niosus** [comment]
@ryanpcmcquen I am thinking about it. I really feel hesitant to add another option to add flags. The original `.clang_complete` file was there because there were people already using this. This one would be yet another option that from my point of view just adds confusion. Can't make up my mind at this point.

**Comment by ryanpcmcquen** [comment]
@niosus, after thinking about it more, I think we should not add support for this file. The documentation clearly states what is allowed. This was a PEBKAC error.

**Comment by niosus** [comment]
I think then I would just close this PR. If you still want to discuss some more, feel free to write here and if you will change your mind and still want this to be integrated, just reopen this PR.

**Pull request closed without merging**
