### PR TITLE
Enable libclang tests on Windows for fixed Sublime Text versions

### PR DESCRIPTION
**Pull request by rchl**
The tests are now passing.

### CODE REVIEW

**Comment by rchl** [comment]
So `test_complete_vector()` test is still disabled for Windows with a comment `disable the windows tests for now until AppVeyor fixes things`. The problem is not with AppVeyor but with the fact that libclang either can't find needed MSVS includes.
```
DEBUG:root: adding error {'row': '10', 'file': 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\include\\\\crtdefs.h', 'col': '10', 'error': "'corecrt.h' file not found"}
```
As for `clang-cl`, it automatically finds MSVS includes (I believe by finding path in the registry). As libclang is not Windows specific, it might not have that functionality. I'll try to figure that out.
If it can't find includes itself, probably the plugin can employ similar technic as clang-cl. We probably don't want user to specify those and also we can't hardcode them as they change with each VS verison.

**Comment by rchl** [comment]
There is a trick[1] to get system include paths from clang: `clang -E -x c++ - -v`
Which produces output like:
```
clang version 3.9.0 (branches/release_39)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
 "C:\\Program Files\\LLVM\\bin\\clang.exe" -cc1 -triple x86_64-pc-windows-msvc19.0.24215 -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -momit-leaf-frame-pointer -v -dwarf-column-info -debugger-tuning=gdb -resource-dir "C:\\Program Files\\LLVM\\bin\\..\\lib\\clang\\3.9.0" -internal-isystem "C:\\Program Files\\LLVM\\bin\\..\\lib\\clang\\3.9.0\\include" -internal-isystem "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\include" -internal-isystem "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0" -fdeprecated-macro -fdebug-compilation-dir "C:\\workspace" -ferror-limit 19 -fmessage-length 0 -fms-extensions -fms-compatibility -fms-compatibility-version=19.0.24215 -std=c++14 -fdelayed-template-parsing -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o - -x c++ -
clang -cc1 version 3.9.0 based upon LLVM 3.9.0 default target x86_64-pc-windows-msvc
#include "..." search starts here:
#include <...> search starts here:
 C:\Program Files\LLVM\bin\..\lib\clang\3.9.0\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0
End of search list.
```
That could in theory be used to pre-populate default include paths for libclang.

That command blocks the stdin though, so it's a bit hacky to use it from the command line.

[1] Source: https://github.com/AndrewWalker/ccsyspath/blob/master/ccsyspath/paths.py

**Comment by rchl** [comment]
Actually that wouldn't help as corecrt.h file in SDK directory:
```
C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/ucrt
C:/Program Files (x86)/Windows Kits/NETFXSDK/4.6.1/include/um
C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/shared
C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/um
C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/winrt
```
And those would probably have to got from registry.

**Comment by niosus** [comment]
Thanks @rchl 
Wanted to enable the tests for libclang since ages. I'll merge as there is now failing osx build, but it is unrelated to this pull request.

Yeah, that comment landed there because at some point appveyor had an update and since then std includes could not be found. Before it was working. I know that they have updated clang to version 3.9 and maybe it searches for std includes in a different way, or ships its own std library. Don't know, didn't have time to look into this one yet.

**Pull request merged**
