### PR TITLE
OS X: Locate correct libclang.dylib.

### PR DESCRIPTION
**Pull request by Ventero**
cf. #23

### CODE REVIEW

**Comment by niosus** [comment]
Hey @Ventero this looks like it won't break anything, but I want to add unit tests for libclang and along with that will merge your contribution. Thanks a lot! It is going to happen either today or tomorrow if nothing goes wrong.

**Comment by niosus** [comment]
Ok, I have merged your suggestion into a separate branch and started adding tests for it. It is not going too good. :) The libclang doesn't like python bindings I provide. 

To push it to master I need it working out of the box. For this I would need proper python bindings for whatever esoteric version osx ships with. I've found this: https://gist.github.com/yamaya/2924292 and it may be helpful. I am testing it now.

Also, you said you were using llvm clang. How hard is it to install? If it is one command I am fine with just adding this to readme and forget about using the system one.

**Comment by Ventero** [comment]
I played around a bit with the system-provided clang/llvm as well while testing things.

Note that I'm still running OS X 10.9 on this machine, so the clang provided by Xcode is version 3.5. So I did the same you did in https://github.com/niosus/EasyClangComplete/commit/1d83a6c3d6e78ee06585397b3982bf06d14f3782, i.e. reduce the default version to 3.5 - and everything still works out of the box when using /usr/bin/clang++ as clang_binary. The libclang.dylib lookup I added also correctly figures out the library directory: `INFO:EasyClangComplete.plugin.completion.lib_complete: setting libclang library dir to /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/../..`.

What issues are you running into exactly?

For people who already have [Homebrew](http://brew.sh/) installed, it is one command to install the latest "stable" LLVM version (`brew install llvm`), or two commands to install any recent LLVM version (`brew tap homebrew/versions; brew install homebrew/versions/llvm38`).

**Comment by niosus** [comment]
Ok, I have noted that it is easy to install some proper llvm, but I will try some more time to make it work with a default one.

The error is the following: https://travis-ci.org/niosus/EasyClangComplete/jobs/134031410#L146
It is late and my brain is not working properly any more, so I can't seem to figure out what to move where.

**Comment by Ventero** [comment]
If I had to guess, that error occurs because `cindex.Config` is initialized when the plugin is first loaded now - so when you later on try to instantiate the `CompleterLib` in the test, `cindex.Config` has already been set up (since your import in the `CompleterLib` ctor essentially picks up the same instance of the module, not a new one).

**Comment by Ventero** [comment]
Added a new commit that avoids attempting to re-initialize the Python bindings if they already are loaded - which seems to fix the issue: https://travis-ci.org/Ventero/EasyClangComplete/jobs/134034038

**Comment by niosus** [comment]
Totally makes sense! Let me briefly test in the branch

**Comment by niosus** [comment]
Nice! No errors anymore. I will add more tests and to a proper merge tomorrow then. Thank you so much for your efforts!

**Comment by niosus** [comment]
Nah, could not wait. Everything is working so merged. Thanks again! :+1:

**Pull request merged**
