### PR TITLE
Add linter mark style setting (#634)

### PR DESCRIPTION
**Pull request by oakmountainapps**
Adds linter mark style setting (#634). This makes it possible to configure how the linter errors/warnings are highlighted in the code.

### CODE REVIEW

**Comment by oakmountainapps** [comment]
Hi! I see above that two checks failed. Although, the errors don't seem related to my patch. I have never uploaded PR before, is it something that I should handle?

**Comment by niosus** [comment]
Thanks for the PR! Generally, don't worry about the build system if it is not related to your changes. Sometimes it doesn't feel like it wants to do what we want it to do 🤷‍♂ 

I will have a look at this and merge it during this week, I guess.

**Comment by niosus** [comment]
Thanks a lot for this PR! Really nice!

**Comment by oakmountainapps** [comment]
Thanks, I'm glad that I could contribute a little bit!

**Pull request merged**
