### PR TITLE
Added gutter dot style

### PR DESCRIPTION
**Pull request by schreda**
Added dot gutter error style

### CODE REVIEW

**Comment by niosus** [comment]
Thanks for fixing the style. Please also update the comments in https://github.com/niosus/EasyClangComplete/blob/54c5274b4bb7ca5d8f24bab6e6a172966face675/EasyClangComplete.sublime-settings#L61

**Comment by niosus** [comment]
@schreda there is no need to close the PR when you need to add something to it. Just keep adding stuff to your `dev` branch. :smiley:

**Comment by schreda** [comment]
Aah. Haha. Already thought, that this is little complicated

**Comment by niosus** [comment]
No worries :)

**Pull request closed without merging**
