### PR TITLE
wildcard support for include_dirs

### LINKED ISSUE #101: Wildcards in include_dirs?
If I set `use_libclang` to `true`, I get errors, like _»field has incomplete type 'const std::string'«_. After I add `/usr/lib/clang/3.8.1/include` to `include_dirs`, these errors disappear.
However, if I set  `use_libclang` to `false`, adding the clang include path is not necessary.
Could it be changed so that adding the path is not necessary with libclang? Or could you add wildcard (like `/usr/lib/clang/*/include`) support?
That way, we would not have to change the path on every clang update.

### PR DESCRIPTION
**Pull request by tastytea**
expands every * in include_dirs.
Fixes #101

### CODE REVIEW

**Comment by niosus** [comment]
Thanks for the pull request! This stuff looks nice to me. However, there is a small issue with that.
Some people may have multiple clangs installed. E.g. on my system I get:
```
DEBUG:EasyClangComplete.plugin.plugin_settings:   adding: /usr/lib/clang/3.8/include
DEBUG:EasyClangComplete.plugin.plugin_settings:   adding: /usr/lib/clang/3.8.0/include
```

Which is logical, but I believe it will break some things for some people. Although, one could argue, that  people with multiple clang installations should then avoid using `*`, there is a better way. 

In the `completer` class I already parse the version of the clang binary in use, so we could use that to replace the wildcard. And one we're at it, I start thinking that a wildcard character is slightly misleading. I would go for something like `$clang_version` or alike. Otherwise people will try to use the wildcard in all the inappropriate places and will file a bunch of bug reports on that not working :smile: 

Whad do you say?

**Comment by tastytea** [comment]
> In the `completer` class I already parse the version of the clang binary in use, so we could use that to replace the wildcard. And one we're at it, I start thinking that a wildcard character is slightly misleading. I would go for something like `$clang_version` or alike. Otherwise people will try to use the wildcard in all the inappropriate places and will file a bunch of bug reports on that not working :smile:

Sounds reasonable to me. I was thinking that wildcards could be useful for other purposes as well. Now that I think about it, nothing comes to mind. :smile:

**Comment by niosus** [comment]
Ok, cool that we are on the same page :)
This seems to be easy to do, so I probably will build on top of your code to do this on the weekend.

**Comment by niosus** [comment]
@tastytea I have built on top of your changes, but I eventually decided to drop the function you had. It was slightly more sophisticated than what I have in the end. I guess it is enough to just replace `$clang_version` string in settings with actual version. 

Please open a new issue if you disagree. For minor discussions, we can stick to talking here. Thanks for the pull request again! Please keep contributing :+1:

**Pull request merged**
