### PR TITLE
Add option to disable cache.

### PR DESCRIPTION
**Pull request by simia**
Add option to disable cache. Not sure if passing settings around is good choice but nothing better comes to my mind at the moment.

### CODE REVIEW

**Comment by niosus** [comment]
Ugh, I really need to fix the Windows builds.... :(

I like the PR and will merge it now.

**Comment by ooJerryLeeoo** [comment]
@niosus I think you should disable cache by default, not just add to option.
What do you think ?

**Comment by niosus** [comment]
No, I disagree. Since nearly one year that this project exists you are the first one who noticed it and I haven't noticed this either while using the plugin every day. I'd rather trade some inaccuracies for speed. I will leave it off by default.

**Comment by ooJerryLeeoo** [comment]
Okay, I see.

**Comment by simia** [comment]
Yeah @niosus is right. With fairly large TU, caching off and autocomplete plugin sometimes gets annoyingly slow.

**Comment by ooJerryLeeoo** [comment]
@simia I agree you at this point.

**Comment by niosus** [comment]
I will try to release the fix today night.

**Pull request merged**
