### PR TITLE
Be style consistent in settings

### PR DESCRIPTION
**Pull request by kgizdov**

### CODE REVIEW

**Comment by niosus** [comment]
Hey @kgizdov thanks for the suggestion. I'm not sure spending more vertical space is a better way, but I don't really mind. But overall I feel that keeping it in one line and just moving the `"["` a bit to the left in the list would be a better solution? What do you say?

**Comment by kgizdov** [comment]
I was thinking of the `"prop": []` convention and things like below in the settings file:
```
  // C++ specific flags. Prepend common_flags for C++ files.
  "cpp_flags" : [
    "-std=c++11"
  ],
```
But if you prefer to keep this on one line, I will change it. Should I also change the `*_flags` to be one liners?

**Comment by niosus** [comment]
I think I would prefer lines that fit in a single line to actually be single line, while those, that don't to span multiple ones. I agree that consistency is important, so yes, if you are already up to this, please make short settings one-liners.

Also, please rebase on `dev`.

**Comment by niosus** [comment]
Thanks!

**Pull request merged**
