### PR TITLE
 Added a setting for popup maximum dimensions in pixels

### PR DESCRIPTION
**Pull request by detly**
See PR #452 .  I initially made this proportional to view size, but there were problems with that. This approach exposes a user setting for maximum dimensions or uses the current hard-coded values as defaults.

It also changes the behaviour to use code wrapping in the popup.

I'm not 100% happy with this approach, since it means users have to pick a lowest-common-dimension amongst any set of screens they might be using. But there's no reliable way to get screen dimensions via Sublime's API, so this is it.

Also note I couldn't figure out how to run the tests. I updated them, but I haven't been able to run them.

### CODE REVIEW

**Comment by niosus** [comment]
I see two types of errors in tests:
- your code does not pass the linter. See [test_style.py](tests/test_style.py) file for details on which commands to run locally to make sure your code passes them.
- you added a couple of lines to the body of the popup and the tests have to be adapted accordingly. You can run tests locally by installing `UnitTesting` package from Package Control and running it against the ECC project.

**Comment by detly** [comment]
Unit tests now pass (as much as they did on `dev` before my changes). PEP8 and PEP257 are clear. (I note that the PEP* tests seem to fail even though the linter programs themselves seem to pass.)

**Comment by detly** [comment]
Let me know if you want me to rebase or squash all the commits together.

**Comment by detly** [comment]
Hmm, passes on Travis under Ubuntu, but fails on OS X. Line ending issue?

**Comment by niosus** [comment]
Probably these are the tests that are only run on OS X. Look at `test_info_objc_class_method_with_return_value_and_parameters` - this tests fails in travis. You will probably need to change the expected popup text there too.

**Comment by detly** [comment]
I actually had, but accidentally removed the trailing EOL as well. Should be good now.

**Comment by niosus** [comment]
Sorry for the delay. I plan to merge this by Sunday. I agree that it's not optimal as the users will have to pick on their own, but I also don't see anything more reliable available for us now. Maybe we could force a certain number of characters in monospace font used by the info window as an alternative. Anyway, this can be added at a later point in time.

**Comment by niosus** [comment]
Ok, I think this looks good to me. Maybe we will need to revisit this at some point to setup the size of the window depending on the number of monospace chars in it, but that is for the future.

**Pull request merged**
