### PR TITLE
Show type declaration on mouse hover popup

### PR DESCRIPTION
**Pull request by dibalavs**
Example:
```c++
typedef struct {
   int a;
   int b;
   int c;
} my_type;
```    
and usage:    
```c++
my_type t;
```
When mouse over "my_type"
Popup without patch:
```
my_type
```  
Popup with patch:
```c++
my_type
 
typedef struct {
  int a;
  int b;
  int c;
} my_type;
````

-----

Hi! Thanks for the PR! To keep things clean, please check the boxes below:

- [x] This PR is set to merge with `dev` branch.
 _(required)_

### CODE REVIEW

**Comment by niosus** [comment]
Thanks for this contribution. How does it scale with big classes?

**Comment by dibalavs** [comment]
I have C structs (I use C as primary language) around 100 lines. It is ok.  Previous patch (with macros body) which uses the same mechanisms (loading part of file) I checked on macroses 300 lines of code.

Which size of class/struct should I check this patch?
Also it is possible to fix patch to strip lines over some threshold.  But what threshold should be?

**Comment by niosus** [comment]
I don't expect it to be a performance problem, but I strive to keep the plugin from overwhelming the user. I feel that showing the whole class in a popup is not something I want to see usually. There is no code highlight there and no navigation. I guess, I like the way it is implemented now by showing the link to the location with the declaration. 

What is your usecase for this feature? Why would you like to see the whole struct in a popup?

**Comment by niosus** [comment]
Also, I think it is related to #226 so there seems to be some demand for this or a version of this. I will play around with your implementation as soon as I find the time (probably on the weekend) and will think how we can integrate it. Thanks again!

**Comment by dibalavs** [comment]
Hello. Sorry for late response. 
When I see popup hover on trype, I want to see original type declaration.
1) for typedefs:
   typedef int my_super_type;
   It is good to see that my_super_type is usual integer type.

2) for structures, it is better to see popup window with whole list of fields, instead of start typing "var." and wait for help. (partially it is my personal preference, recenty I used eclipse IDE, which has the same popup,  for me it was very helpful)

3) for classes, may be it is not very good idea to show all members, but in c++ classes are very similar to structures, so I think we should have the same behavior for both of classes/structures.

**Comment by niosus** [comment]
Hey @dibalavs 
I've looked at how this works with classes and it works decently well with relatively large classes. And I definitely see the value in this. However, as different people have different preferences, I would suggest hiding this functionality behind a settings flag. This way people who like it will be able to use it, while the ones who don't can turn it off. 

Would you be interested in doing this step? I could also do this, but this, again, will take time. Tell me what you think and thanks again for the contribution.

**Comment by dibalavs** [comment]
>  I would suggest hiding this functionality behind a settings flag. This way people who like it will be able to use it, while the ones who don't can turn it off.

Ok. I will do it.

**Comment by dibalavs** [comment]
what default value should be for this setting?

**Comment by niosus** [comment]
Let's go for `true` by default. I like the feature and will be happy to use it, but we must provide a way to disable it should it be too annoying for some people working with header-only libraries for example.

**Comment by niosus** [comment]
Hey @dibalavs thanks for fixing the conflicts. I have looked into this repo: https://github.com/facelessuser/sublime-markdown-popups

It allows to highlight the code in a markdown, which looks really promising. I guess, I will build upon your PR and will transition the whole plugin to that frontend allowing to show highlighted code in the popup.

**Comment by niosus** [comment]
Ok, now I should have some more time on my hands :) I've looked at the PR and everything seems good to  me. Will merge it now.

**Pull request merged**
